name: workflow_proj2

on:
  push:
    branches:
      - feature-branch  # Change this to the specific branch name
  pull_request:
    branches:
      - feature-branch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
