name: workflow_proj2

on:
  push:
    branches:
      - main  # Replace with the name of the branch where you want to trigger the workflow
      - develop  # You can add multiple branches like this
  pull_request:
    branches:
      - main  # Workflow runs on pull requests targeting the 'main' branch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
