name: workflow_proj2

on: [workflow_dispatch]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest  # Change this line to use a GitHub-hosted runner
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
